[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "HCnonKjpqkuqPhf37N8kwULNpK1PX3FFojDddKd6rQeb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = 'C:\Users\ttisl\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
